chore: Update deploy.yaml workflow to fix agent config file path and clone Depictio-CLI repository

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -30,14 +30,31 @@ jobs:
       - name: Start Docker Compose Services
         run: docker compose up -d
 
+      - name: List Files
+        run: ls -la
+
       - name: Wait for Services to Start
-        run: sleep 60  # Adjust the wait time if necessary
+        run: sleep 10  # Adjust the wait time if necessary
+
+      # Step 5: Verify All Containers Are Running
+      - name: Check if all containers are running
+        run: |
+          # Check if any containers are not in the 'Up' state
+          if ! docker compose ps | grep -q 'Up'; then
+            echo "One or more containers are not running. Failing the step."
+            docker compose ps
+            exit 1
+          fi
+
+
 
       - name: Make sure all Services Are Running
         run: |
           docker ps
           docker logs depictio_frontend
           docker logs depictio_backend
+
+
 
         # Clone the depictio-cli repository
       - name: Clone Depictio-CLI Repository
